# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Middleware.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 494)
        MainWindow.setMaximumSize(QtCore.QSize(622, 494))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 440, 581, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 601, 431))
        self.widget.setObjectName("widget")
        self.list_groupBox = QtWidgets.QGroupBox(self.widget)
        self.list_groupBox.setGeometry(QtCore.QRect(10, 90, 581, 331))
        self.list_groupBox.setTitle("")
        self.list_groupBox.setObjectName("list_groupBox")
        self.left_list_groupBox = QtWidgets.QGroupBox(self.list_groupBox)
        self.left_list_groupBox.setGeometry(QtCore.QRect(10, 10, 240, 311))
        self.left_list_groupBox.setObjectName("left_list_groupBox")
        self.left_tableWidget = QtWidgets.QTableWidget(self.left_list_groupBox)
        self.left_tableWidget.setGeometry(QtCore.QRect(7, 17, 225, 286))
        self.left_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.left_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.left_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.left_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.left_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.left_tableWidget.setObjectName("left_tableWidget")
        self.left_tableWidget.setColumnCount(2)
        self.left_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.left_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.left_tableWidget.setHorizontalHeaderItem(1, item)
        self.left_tableWidget.horizontalHeader().setDefaultSectionSize(110)
        self.left_tableWidget.horizontalHeader().setHighlightSections(False)
        self.left_tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.left_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.left_tableWidget.verticalHeader().setVisible(False)
        self.right_list_groupBox = QtWidgets.QGroupBox(self.list_groupBox)
        self.right_list_groupBox.setGeometry(QtCore.QRect(330, 10, 240, 311))
        self.right_list_groupBox.setObjectName("right_list_groupBox")
        self.right_tableWidget = QtWidgets.QTableWidget(self.right_list_groupBox)
        self.right_tableWidget.setGeometry(QtCore.QRect(7, 17, 225, 286))
        self.right_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.right_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.right_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.right_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.right_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.right_tableWidget.setObjectName("right_tableWidget")
        self.right_tableWidget.setColumnCount(2)
        self.right_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.right_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.right_tableWidget.setHorizontalHeaderItem(1, item)
        self.right_tableWidget.horizontalHeader().setDefaultSectionSize(110)
        self.right_tableWidget.horizontalHeader().setHighlightSections(False)
        self.right_tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.right_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.right_tableWidget.verticalHeader().setVisible(False)
        self.move2right_pushButton = QtWidgets.QPushButton(self.list_groupBox)
        self.move2right_pushButton.setGeometry(QtCore.QRect(262, 86, 51, 41))
        self.move2right_pushButton.setObjectName("move2right_pushButton")
        self.move2left_pushButton = QtWidgets.QPushButton(self.list_groupBox)
        self.move2left_pushButton.setGeometry(QtCore.QRect(262, 180, 51, 41))
        self.move2left_pushButton.setObjectName("move2left_pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 71))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(280, 34, 54, 12))
        self.label_3.setObjectName("label_3")
        self.db_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.db_comboBox.setGeometry(QtCore.QRect(160, 30, 91, 22))
        self.db_comboBox.setObjectName("db_comboBox")
        self.tb_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.tb_comboBox.setGeometry(QtCore.QRect(330, 30, 91, 22))
        self.tb_comboBox.setObjectName("tb_comboBox")
        self.login_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.login_pushButton.setGeometry(QtCore.QRect(20, 30, 61, 23))
        self.login_pushButton.setObjectName("login_pushButton")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(110, 34, 54, 12))
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 10, 141, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.apply_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.apply_pushButton.setGeometry(QtCore.QRect(34, 30, 75, 23))
        self.apply_pushButton.setObjectName("apply_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据库加密中间件"))
        self.left_list_groupBox.setTitle(_translate("MainWindow", "未加密列表"))
        self.left_tableWidget.setSortingEnabled(True)
        item = self.left_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名称"))
        item = self.left_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类型"))
        self.right_list_groupBox.setTitle(_translate("MainWindow", "加密列表"))
        self.right_tableWidget.setSortingEnabled(True)
        item = self.right_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名称"))
        item = self.right_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类型"))
        self.move2right_pushButton.setText(_translate("MainWindow", ">>"))
        self.move2left_pushButton.setText(_translate("MainWindow", "<<"))
        self.groupBox.setTitle(_translate("MainWindow", "数据库登录与连接"))
        self.label_3.setText(_translate("MainWindow", "数据表："))
        self.login_pushButton.setText(_translate("MainWindow", "登录"))
        self.label_4.setText(_translate("MainWindow", "数据库："))
        self.groupBox_2.setTitle(_translate("MainWindow", "执行操作"))
        self.apply_pushButton.setText(_translate("MainWindow", "应用修改"))
